CREATE DATABASE IF NOT EXISTS <DEV_DATABASE>;

USE DATABASE <DEV_DATABASE>;

CREATE SCHEMA IF NOT EXISTS INVENTORY_DIFF_APP;
USE SCHEMA INVENTORY_DIFF_APP;

CREATE TABLE IF NOT EXISTS INVENTORY_SNAPSHOT (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR,
    STORE_NAME VARCHAR,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    SYSTEM_STOCK_QTY NUMBER
);

CREATE TABLE IF NOT EXISTS PHYSICAL_INVENTORY_COUNTS (
    COUNT_DATE DATE,
    STORE_ID VARCHAR,
    STORE_NAME VARCHAR,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    ACTUAL_STOCK_QTY NUMBER,
    UPLOADED_AT TIMESTAMP_NTZ,
    UPLOADED_BY VARCHAR
);
